# This defines the name of the workflow that appears in the GitHub Actions pipeline dashboard.
name: CICD

on:
    #This means the pipeline runs manually from GitHub UI.
  workflow_dispatch:
    inputs:
      environment:
        description: This is environment where this workflows runs
        default: 'dev'
        required: true
        type: choice
        options:
          - dev
          - prod
          - staging

jobs:

  code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        run: echo "Code clone from GitHub"
        
  build:
    runs-on: ubuntu-latest
    needs: code
    steps:
      - name: Build the Docker container
        run: echo "Docker build container"
 test:
   runs-on: ubuntu-latest
   needs: build
   steps:
     - name: Test the Docker container
       run: echo "Test the docker container"
       
 deploy:
   runs-on: ubuntu-latest
   if: inputs.environment == 'dev'
   needs: test
   steps:
     - name: Deploy the Contaienr  run: echo "Deploy the container"
       run: echo "docker compose up -d"
       
